"use client";

import { motion } from "framer-motion";
import { ImageOff } from "lucide-react";
import { useGalleryItems } from "@/lib/hooks/use-gallery";
import { LandingNav } from "@/components/landing/LandingNav";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { SiteBanner } from "@/components/shared/SiteBanner";

function FadeIn({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-40px" }}
      transition={{ duration: 0.5, delay, ease: [0.25, 0.46, 0.45, 0.94] }}
    >
      {children}
    </motion.div>
  );
}

/**
 * Public showcase — a separate page rather than a landing-page section on
 * purpose, since this is browsable/growing content (best user + admin
 * output), not a fixed marketing pitch the way the landing sections are.
 * Reads directly from Supabase via useGalleryItems() (see that hook for why:
 * same anon-key-direct pattern as templates/hero images, RLS-gated to
 * approved rows only), so there's nothing for this page itself to
 * authorize — everything it can see is already public.
 */
export default function GalleryPage() {
  const { items, loading, error } = useGalleryItems();

  return (
    <div className="text-white min-h-screen" style={{ background: "#0f0404" }}>
      <SiteBanner />
      <LandingNav />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-10 md:py-16">
        <FadeIn>
          <p
            className="text-[11px] font-bold uppercase tracking-[0.2em] mb-3"
            style={{ color: "#f87171" }}
          >
            Gallery
          </p>
          <h1
            className="font-black tracking-tight leading-[0.95] mb-3"
            style={{ fontSize: "clamp(2.2rem,4.5vw,4.2rem)" }}
          >
            Real output,
            <br />
            <span style={{ color: "rgba(255,255,255,0.2)", fontWeight: 300 }}>
              hand-picked
            </span>
          </h1>
          <p className="text-sm max-w-xl mb-10" style={{ color: "rgba(255,255,255,0.5)" }}>
            Images and videos generated by OpusGen AI, submitted by users and reviewed by our team.
          </p>
        </FadeIn>

        {loading ? (
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2.5 sm:gap-3">
            {Array.from({ length: 8 }).map((_, i) => (
              <div
                key={i}
                className="aspect-[3/4] rounded-2xl animate-pulse"
                style={{ background: "rgba(255,255,255,0.04)" }}
              />
            ))}
          </div>
        ) : error ? (
          <div className="flex flex-col items-center justify-center gap-3 py-24">
            <p className="text-sm" style={{ color: "rgba(255,255,255,0.45)" }}>Couldn&apos;t load the gallery.</p>
          </div>
        ) : items.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-3 py-24 text-center">
            <ImageOff className="w-8 h-8" style={{ color: "rgba(255,255,255,0.2)" }} />
            <p className="text-sm" style={{ color: "rgba(255,255,255,0.45)" }}>
              Nothing here yet — check back soon.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2.5 sm:gap-3">
            {items.map((item, i) => (
              <FadeIn key={item.id} delay={Math.min(i, 8) * 0.04}>
                <div
                  className="relative rounded-2xl overflow-hidden aspect-[3/4]"
                  style={{ border: "1px solid rgba(255,255,255,0.08)", background: "#140505" }}
                >
                  {item.mediaType === "video" ? (
                    <video
                      src={item.mediaUrl}
                      poster={item.coverImageUrl ?? undefined}
                      autoPlay muted loop playsInline preload="auto"
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={item.mediaUrl} alt={item.caption ?? "Gallery output"} className="w-full h-full object-cover" />
                  )}
                  {item.caption && (
                    <div
                      className="absolute inset-x-0 bottom-0 p-3 pt-8"
                      style={{ background: "linear-gradient(0deg, rgba(0,0,0,0.75) 0%, transparent 100%)" }}
                    >
                      <p className="text-xs leading-snug line-clamp-2" style={{ color: "rgba(255,255,255,0.85)" }}>
                        {item.caption}
                      </p>
                    </div>
                  )}
                </div>
              </FadeIn>
            ))}
          </div>
        )}
      </main>

      <LandingFooter />
    </div>
  );
}
